### ISSUE TITLE
SQ610RF might also be supported

### ISSUE THREAD

**Issue by Ashden** [adrmnt/salus-it600-pack#1]
Hello,

Using this repo indirectly through the HomeBridge plugin. Noticed that my thermostats weren't picked up. Then I changed this line:
https://github.com/adrmnt/salus-it600-pack/blob/1653b8cb9462b88286c791be08a11cc950e268d1/index.js#L17
to my thermostat model ('SQ610RF') and it works. 
Is there such a big difference between these two models, or will you add this model as well?

Thanks.

**Comment by xyz4tech** [comment]
Thanks for this advice. I tested it on my homebridge instance and was able to work with it in a short test.

**Comment by adrmnt** [comment]
Hi @Ashden, @xyz4tech,

I'm happy to see that someone is using this plugin. 
Can you push your fix?

**Comment by adrmnt** [comment]
@Ashden , @xyz4tech 
I've updated the plugin. Update it and please specify the thermostat model in config

**Comment by adrmnt** [comment]
fixed

**Comment by bimusiek** [comment]
If someone is interested, here is the homebridge plugin for Salus SQ610: https://github.com/Hernas/homebridge-salus-sq610
