### ISSUE TITLE
status currently not reported

### ISSUE THREAD

**Issue by xyz4tech** [adrmnt/salus-it600-pack#2]
The status is not currently reported. The current status is "off/ standby" all the time. So the icon in HomeKit is always grey. The holding/ heating status (orange and green icon) has stopped working. In the past at least the orange icon was visible in HomeKit during heating. 

Does anyone else having the issue? I tried already to restart Homebridge.

**Comment by xyz4tech** [comment]
did some minor changes

- replacing "===" by "=="
- replacing "!==" by "!="
- replacing "RunningMode" by "RunningState"

seems to report the heating status again

`"use strict";

const https = require('https')
var parse = require('fast-json-parse')

const baseUrl = "eu.salusconnect.io";
const loginUrl = "/users/sign_in.json?";
const apiVersion = "/apiv1";
const devicesUrl = "/devices.json?";

const prop = "ep_9:sIT600TH:";
const propTemperature = prop + "LocalTemperature_x100";
const propHumidity = prop + "SunnySetpoint_x100";
const propHeatingSetpoint = prop + "HeatingSetpoint_x100";
const propRunningMode = prop + "RunningState";

class Index {

    constructor({username, password, thermostatModel}) {
        this.username = username;
        this.password = password;
        this.thermostatModel = thermostatModel;
    }

    async getToken() {
        await this.login();

        function Token(value, creationDay) {
            this.value = value;
            this.creationDay = creationDay;
        }

        return new Token(this.token, new Date().getDate());
    }

    login() {
        return new Promise((resolve, reject) => {
            const data = JSON.stringify({user: {email: this.username, password: this.password}})
            const options = {
                host: baseUrl,
                port: 443,
                path: loginUrl + this.appendTimestamp(),
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Content-Length': data.length
                }
            }

            const req = https.request(options, res => {
                res.on('data', d => {
                    this.token = parse(d.toString()).value.access_token;
                    resolve(this.token);
                })
            })
            req.on('error', error => {
                console.error(error)
            })
            req.write(data)
            req.end()
        })
    }

    async getDevices(token) {
        if (token != null) {
            const allDevices = await this.getData(token, apiVersion + devicesUrl + this.appendTimestamp());

            function Item(id, name, current, target, heating, humidity) {
                this.id = id;
                this.name = name;
                this.current = current;
                this.target = target;
                this.heating = heating;
                this.humidity = humidity;
            }

            const result = [];
            try {
                for (const e of allDevices.value) {
                    const device = e.device;
                    if (device.oem_model == this.thermostatModel.toUpperCase()) {
                        const current = this.getData(token, apiVersion + "/dsns/" + device.dsn + "/properties/" + propTemperature + ".json?" + this.appendTimestamp());
                        const target = this.getData(token, apiVersion + "/dsns/" + device.dsn + "/properties/" + propHeatingSetpoint + ".json?" + this.appendTimestamp());
                        const heating = this.getData(token, apiVersion + "/dsns/" + device.dsn + "/properties/" + propRunningMode + ".json?" + this.appendTimestamp());
                        const humidity = this.getData(token, apiVersion + "/dsns/" + device.dsn + "/properties/" + propHumidity + ".json?" + this.appendTimestamp());

                        await Promise.all([current, target, heating, humidity]).then((values) => {
                            result.push(new Item(device.dsn, device.product_name, values[0].value.property.value / 100, values[1].value.property.value / 100, values[2].value.property.value != 0 ? true : false, values[3].value.property.value));
                        });
                    }
                }
                return result;
            } catch (error) {
                console.error(error);
            }
        } else {
            console.warn("Salus login failed");
        }
    }


    async getDeviceCurrentTemperature(token, id) {
        return (await this.getData(token, apiVersion + "/dsns/" + id + "/properties/" + propTemperature + ".json?" + this.appendTimestamp())).value.property.value / 100;
    }

    async getDeviceTargetTemperature(token, id) {
        return (await this.getData(token, apiVersion + "/dsns/" + id + "/properties/" + propHeatingSetpoint + ".json?" + this.appendTimestamp())).value.property.value / 100;
    }

    async getDeviceHeating(token, id) {
        return (await this.getData(token, apiVersion + "/dsns/" + id + "/properties/" + propRunningMode + ".json?" + this.appendTimestamp())).value.property.value != 0 ? true : false;
    }

    async getDeviceCurrentRelativeHumidity(token, id) {
        return (await this.getData(token, apiVersion + "/dsns/" + id + "/properties/" + propHumidity + ".json?" + this.appendTimestamp())).value.property.value;
    }

    getData(token, path) {
        return new Promise((resolve, reject) => {
            const options = {
                host: baseUrl,
                port: 443,
                path: path,
                method: 'GET',
                headers: {
                    'Authorization': 'Bearer ' + token
                }
            }

            const req = https.request(options, res => {
                res.on('data', d => {
                    resolve(parse(d.toString()));
                })
            })
            req.on('error', error => {
                reject(error);
            })
            req.end()
        })
    }

    async updateTemperature(token, id, temperature) {
        return new Promise((resolve, reject) => {
            if (!id || !temperature)
                throw new Error("Both ID and temperature named arguments must be set");

            const data = JSON.stringify({"datapoint": {"value": temperature * 100}})
            const options = {
                host: baseUrl,
                port: 443,
                path: apiVersion + "/dsns/" + id + "/properties/ep_9:sIT600TH:SetHeatingSetpoint_x100/datapoints.json?" + this.appendTimestamp(),
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Content-Length': data.length,
                    'Authorization': 'Bearer ' + token
                }
            }

            const req = https.request(options, res => {
                resolve(res.statusCode);
            })
            req.on('error', error => {
                console.error(error)
            })
            req.write(data)
            req.end()
        })
    }

    appendTimestamp() {
        return "timestamp=" + new Date().getTime();
    }
}

module.exports = Index;`

**Comment by adrmnt** [comment]
@xyz4tech 
@DragosFlorea fixed this issue.
