### ISSUE TITLE
Added and updated state function

### ISSUE THREAD

**Issue by xyz4tech** [adrmnt/salus-it600-pack#6]
The state function was added and updated to the plugin (green, orange and gray colors now work in the Home app). Unfortunately I was working on a code basis before @zlugg added his fixes. So it is necessary to add his fixes again. Sorry.

**Comment by adrmnt** [comment]
@xyz4tech can you update the PR then? Thank you!

**Comment by zlugg** [comment]
I merged xyz4tech's PR into my latest PR: https://github.com/adrmnt/salus-it600-pack/pull/7

**Comment by adrmnt** [comment]
merged
